In [1]:
import numpy as np

In [2]:
from numpy import doc

In [3]:
help(doc)

Help on package numpy.doc in numpy:

NAME
    numpy.doc

DESCRIPTION
    Topical documentation
    
    The following topics are available:
    
    - constants
    - ufuncs
    
    You can view them by
    
    >>> help(np.doc.TOPIC)                                      #doctest: +SKIP

PACKAGE CONTENTS
    constants
    ufuncs

DATA
    __all__ = ['constants', 'ufuncs', '__doc__']

FILE
    c:\users\datas\anaconda3\lib\site-packages\numpy\doc\__init__.py




In [4]:
?np.array

In [5]:
np.array([1, 2, 3])

array([1, 2, 3])

In [6]:
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [7]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [8]:
np.array([1, 2, 3], ndmin=2)

array([[1, 2, 3]])

In [9]:
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [10]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i4'),('b','<i4')])
x['a']

array([1, 3])

In [11]:
np.array(np.mat('1 2; 3 4'))

array([[1, 2],
       [3, 4]])

In [12]:
np.array(np.mat('1 2; 3 4'), subok=True)

matrix([[1, 2],
        [3, 4]])

# zeros

In [13]:
?np.zeros

In [14]:
np.zeros(10,dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.zeros(10,dtype="float")

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros(10,dtype="complex")

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j])

In [17]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.zeros([5,5],dtype="int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [19]:
s = (2,2)
np.zeros(s)

array([[0., 0.],
       [0., 0.]])

# ones

In [20]:
?np.ones

In [21]:
np.ones(10,dtype="int")

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [22]:
np.ones(10,dtype="float")

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.ones(10,dtype="complex")

array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j,
       1.+0.j, 1.+0.j])

In [24]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.ones([5,5],dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
s = (2,2)
np.ones(s)

array([[1., 1.],
       [1., 1.]])

# eye

In [27]:
?np.eye

In [28]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [29]:
np.eye(3,2, dtype=int)

array([[1, 0],
       [0, 1],
       [0, 0]])

In [30]:
np.eye(4,3, dtype=int,k=1)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [31]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [32]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

# linspace

In [33]:
?np.linspace

In [34]:
np.linspace(10,15,5)

array([10.  , 11.25, 12.5 , 13.75, 15.  ])

In [35]:
## np.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None,axis=0,)

In [36]:
x=np.linspace(10,30,num=25)
# 10 dan 30 a kadar 25 tane sayı

In [37]:
x.ndim

1

In [38]:
x.shape

(25,)

In [39]:
type(x)

numpy.ndarray

In [40]:
x

array([10.        , 10.83333333, 11.66666667, 12.5       , 13.33333333,
       14.16666667, 15.        , 15.83333333, 16.66666667, 17.5       ,
       18.33333333, 19.16666667, 20.        , 20.83333333, 21.66666667,
       22.5       , 23.33333333, 24.16666667, 25.        , 25.83333333,
       26.66666667, 27.5       , 28.33333333, 29.16666667, 30.        ])

In [41]:
y=np.linspace(0,25,num=25)

In [42]:
y

array([ 0.        ,  1.04166667,  2.08333333,  3.125     ,  4.16666667,
        5.20833333,  6.25      ,  7.29166667,  8.33333333,  9.375     ,
       10.41666667, 11.45833333, 12.5       , 13.54166667, 14.58333333,
       15.625     , 16.66666667, 17.70833333, 18.75      , 19.79166667,
       20.83333333, 21.875     , 22.91666667, 23.95833333, 25.        ])

# random

In [43]:
?np.random

In [44]:
?np.random.rand

In [45]:
np.random.rand(3,2)

array([[0.24413418, 0.45981925],
       [0.25566461, 0.98747911],
       [0.84115862, 0.77999695]])

In [46]:
np.random.rand(2,2)

array([[0.64424244, 0.12915318],
       [0.28339917, 0.65909943]])

In [47]:
np.random.rand(2)

array([0.74640866, 0.43246631])

In [48]:
np.random.rand(7)

array([0.23557992, 0.8805886 , 0.82377243, 0.5207605 , 0.65078049,
       0.24954439, 0.14833386])

In [49]:
np.random.normal(20,5,(4,4))

array([[20.65421512, 21.02680779, 27.30108906, 17.23395562],
       [18.4131442 , 15.18805015, 26.28424694, 26.34373739],
       [11.59004402, 16.46980453, 17.99306267, 16.70132318],
       [ 6.39852158, 26.95441075, 23.33742024, 23.57273389]])

In [50]:
np.random.normal(5,20,(4,4))

array([[ -9.51813433,   6.93382939,  44.4255338 ,  -0.69136238],
       [-13.81623258, -11.4117349 , -14.56728002,  -3.51229495],
       [-14.76129631, -16.46430323, -17.69203823,  12.27179359],
       [ 11.06621153, -28.82767632,   8.94744789, -12.26303915]])

In [51]:
np.random.randint(5,20,(4,4))

array([[10, 16, 11, 15],
       [18, 14,  8, 18],
       [ 6, 13, 15, 19],
       [10, 18,  7, 13]])

# ndim, shape, size, dtype

In [52]:
matrix = np.random.randint(5,20,(4,4))

In [53]:
matrix.ndim

2

In [54]:
matrix.shape

(4, 4)

In [55]:
matrix.size

16

In [56]:
matrix.dtype

dtype('int32')

# reshape

In [57]:
rs = np.arange(1,16)

In [58]:
rs

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [59]:
rs.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [60]:
rs.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

# max,argmax

In [61]:
max_argmax = np.arange(0,50,10)

In [62]:
max_argmax

array([ 0, 10, 20, 30, 40])

In [63]:
max_argmax.max()

40

In [64]:
max_argmax1 = np.random.randint(0,10,50)

In [65]:
max_argmax1

array([5, 6, 4, 9, 7, 6, 9, 2, 0, 9, 8, 2, 0, 0, 4, 2, 0, 7, 4, 3, 8, 9,
       8, 3, 9, 7, 2, 8, 3, 6, 5, 7, 5, 9, 5, 5, 4, 0, 1, 6, 2, 7, 2, 0,
       9, 9, 0, 9, 8, 3])

In [66]:
max_argmax1.max()

9

In [67]:
max_argmax1.argmax()

3

In [68]:
max_argmax2 = np.random.randint(0,10,(5,2))

In [69]:
max_argmax2

array([[6, 3],
       [7, 4],
       [4, 9],
       [2, 6],
       [4, 1]])

In [70]:
max_argmax2.max()

9

In [71]:
max_argmax2.argmax()

5

# min,argmin

In [72]:
min_argmin = np.arange(0,50,10)

In [73]:
min_argmin

array([ 0, 10, 20, 30, 40])

In [74]:
min_argmin.min()

0

In [75]:
min_argmin1 = np.random.randint(0,10,50)

In [76]:
min_argmin1

array([9, 9, 7, 2, 0, 7, 8, 0, 2, 5, 7, 2, 8, 6, 7, 1, 1, 8, 3, 4, 5, 1,
       8, 3, 9, 2, 5, 3, 1, 4, 4, 6, 8, 3, 8, 1, 9, 9, 4, 1, 6, 1, 6, 0,
       9, 0, 2, 6, 4, 5])

In [77]:
min_argmin1.min()

0

In [78]:
min_argmin1.argmin()

4

In [79]:
min_argmin2 = np.random.randint(0,10,(5,2))

In [80]:
min_argmin2

array([[6, 8],
       [6, 2],
       [8, 4],
       [4, 4],
       [8, 6]])

In [81]:
min_argmin2.min()

2

In [82]:
min_argmin2.argmin()

3

# concatenate

In [83]:
array1 = np.array([0,5,10,15,20,25])
array2 = np.array([30,35,40,45,50,55])

In [84]:
?np.concatenate

In [85]:
## concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

In [86]:
np.concatenate([array1,array2])

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [87]:
np.concatenate((array1,array2))

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [88]:
np.concatenate((array1,array2),axis = 0)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [89]:
array3 = ([1,2,3],[4,5,6])
array4 = ([7,8,9],[10,11,12])

In [90]:
np.concatenate((array3,array4))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [91]:
np.concatenate((array3,array4),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# split

In [92]:
array = np.array([1,3,5,50,50,2,4,6])

In [93]:
?np.split

In [94]:
np.split(array,[3])

[array([1, 3, 5]), array([50, 50,  2,  4,  6])]

In [95]:
np.split(array,[5])

[array([ 1,  3,  5, 50, 50]), array([2, 4, 6])]

In [96]:
np.split(array,[3,5])

[array([1, 3, 5]), array([50, 50]), array([2, 4, 6])]

In [97]:
array1 = np.array([1,3,5,50,50,2,4,6,0,0,0,0])

In [98]:
np.split(array1,[3,5,8])

[array([1, 3, 5]), array([50, 50]), array([2, 4, 6]), array([0, 0, 0, 0])]

In [99]:
x,y,z,t = np.split(array1,[3,5,8])

In [100]:
x

array([1, 3, 5])

In [101]:
y

array([50, 50])

In [102]:
z

array([2, 4, 6])

In [103]:
t

array([0, 0, 0, 0])

In [104]:
array1 = np.array([1,3,5,50,50,2,4,6,0,0,0,0])

In [105]:
array1.ndim

1

In [106]:
array1.shape

(12,)

In [107]:
np.split(array1,4)

[array([1, 3, 5]), array([50, 50,  2]), array([4, 6, 0]), array([0, 0, 0])]

In [108]:
a,b,c,d = np.split(array1,4)

In [109]:
a

array([1, 3, 5])

In [110]:
b
c

array([4, 6, 0])

In [111]:
d

array([0, 0, 0])

# çok boyutlu split

In [112]:
array = np.arange(0,20).reshape(5,4)

In [113]:
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [114]:
np.split(array,[1,3])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [115]:
x,y,z = np.split(array,[1,3])

In [116]:
x

array([[0, 1, 2, 3]])

In [117]:
y

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [118]:
z

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [119]:
x,y,z = np.split(array,[1,3],axis=1)

In [120]:
x

array([[ 0],
       [ 4],
       [ 8],
       [12],
       [16]])

In [121]:
y

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [122]:
z

array([[ 3],
       [ 7],
       [11],
       [15],
       [19]])

In [123]:
np.hsplit(array,[1,3])

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [124]:
np.hsplit(array,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [125]:
np.vsplit(array,5)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [126]:
np.vsplit(array,[2,5])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]),
 array([], shape=(0, 4), dtype=int32)]

# sort

In [127]:
variable = np.array([3,5,1,7,9,8,6,2,4])

In [128]:
np.sort(variable)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
variable = np.sort(variable)

In [130]:
variable

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
example = np.random.normal(30,10,(4,4))

In [132]:
example

array([[21.38620792, 19.99897466, 20.05467505, 27.18850814],
       [31.65495514, 39.42845009, 39.8212744 , 13.90770526],
       [ 7.29055821, 34.80441276, 43.01207322, 10.39488941],
       [42.10993851, 35.87518317, 40.1931868 , 17.62198621]])

In [133]:
np.sort(example)

array([[19.99897466, 20.05467505, 21.38620792, 27.18850814],
       [13.90770526, 31.65495514, 39.42845009, 39.8212744 ],
       [ 7.29055821, 10.39488941, 34.80441276, 43.01207322],
       [17.62198621, 35.87518317, 40.1931868 , 42.10993851]])

In [134]:
np.sort(example,axis=1)

array([[19.99897466, 20.05467505, 21.38620792, 27.18850814],
       [13.90770526, 31.65495514, 39.42845009, 39.8212744 ],
       [ 7.29055821, 10.39488941, 34.80441276, 43.01207322],
       [17.62198621, 35.87518317, 40.1931868 , 42.10993851]])

# index

In [135]:
variable

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
variable[0:4]

array([1, 2, 3, 4])

In [137]:
variable[:4:2]

array([1, 3])

In [138]:
variable[::3]

array([1, 4, 7])

In [139]:
variable1 = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [140]:
variable1

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [141]:
variable1[0,0]

5

In [142]:
variable1[0:1,0:1]

array([[5]])

In [143]:
variable1[0:2,0:2]

array([[ 5, 10],
       [20, 25]])

In [144]:
variable1[1:2,2:3]

array([[30]])

In [145]:
variable1[0:2,1:3]

array([[10, 15],
       [25, 30]])

In [146]:
a =np.array([1,2,3,9,5,6])

In [147]:
a[3]

9

In [148]:
a[3] = 4

In [149]:
a

array([1, 2, 3, 4, 5, 6])

In [150]:
b = np.array([[5,10,15],[20,25,30],[35,40,45],[11,11,11]])

In [151]:
b

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [11, 11, 11]])

In [152]:
b[3]

array([11, 11, 11])

In [153]:
b[3] = 50,55,60

In [154]:
b

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

In [155]:
array = np.arange(0,11)

In [156]:
array<5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False])

In [157]:
array[array<5]

array([0, 1, 2, 3, 4])

In [158]:
condition = array >7

In [159]:
array[condition]

array([ 8,  9, 10])

In [160]:
array - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [161]:
array * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [162]:
array * array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

# ufunc

In [163]:
np.subtract(array,2)

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [164]:
np.multiply(array,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [165]:
np.add(array,2)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [166]:
np.divide(array,2)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [167]:
np.power(array,2)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [168]:
np.sqrt(100)

10.0

In [169]:
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [170]:
np.mod(array,2)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [171]:
np.sin(180)

-0.8011526357338304

In [172]:
np.cos(180)

-0.5984600690578581

In [173]:
np.tan(180)

1.3386902103511544

In [174]:
1/np.tan(180)

0.7469988144140444

In [175]:
np.log(array)

C:\Users\datas\AppData\Local\Temp\ipykernel_10092\3382134483.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(array)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [176]:
np.sum(array)

55

In [177]:
np.mean(array)

5.0

In [178]:
np.median(array)

5.0

In [179]:
np.std(array)

3.1622776601683795

In [180]:
np.var(array)

10.0

In [181]:
np.sqrt(np.var(array))

3.1622776601683795

# linalg() solve

# 2x1+x2=5
# -3x1+6x2=0

In [182]:
coefficient = np.array([[2,1],[-3,6]])

In [183]:
output = np.array([5,0])

In [184]:
np.linalg.solve(coefficient,output)

array([2., 1.])